### ISSUE TITLE
本地部署章节错误

### ISSUE THREAD

**Issue by Axi404** [xjtu-ai/xjtu-ai.github.io#5]
在本地预览这一 section 中提到了拉取 git submodule 的方式：

```bash
git submodule sync
```

根据我的了解，这一操作用于将 .gitsubmodules 中的配置信息同步到 .git/config 里面，而非用于拉取。如果需要使用拉取，可以使用 `git submodule update`，而对于递归式地初始化并且更新，可以使用 `--init` 以及 ` --recursive` 参数，也就是说这一部分可以更改为：

```bash
git submodule sync
git submodule update --init --recursive
mkdocs serve # server on localhost:8000
```

假如 maintainers 认为是正确的，我会开始一个 PR 来修复这个问题。

**Comment by ShwStone** [comment]
111很有道理

**Comment by Axi404** [comment]
@ShwStone 我已经开启了一个 PR 以修复这个问题 #6
